name: Convert sigma rules to splunk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Install Sigma CLI plugins
      run: sigma plugin install splunk
    - name: Check validity of Sigma rules
      run: |
        for file in rules/sigma/*.yml; do
          sigma check $file
        done
    - name: Convert Sigma rules to Splunk
      run: |
        for file in rules/sigma/*.yml; do
          splunk_filename=$(echo $file | sed 's/sigma/splunk/' | sed 's/.yml$/.spl/')
          sigma convert -t splunk -p splunk_windows $file -o $splunk_filename
        done
    - name: Commit and push changes
      run: |
        git add -N rules/splunk
        if [ -z "$(git diff --exit-code)" ]; then
          echo "No changes to commit"
          exit 0
        else
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add rules/splunk
          git commit -m "Convert Sigma rules to Splunk"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
