name: Publish pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Set up data
      run: python data_setup.py
      env:
        BASE_URL: '${{ github.server_url }}/${{ github.repository }}'

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM dependencies
      run: npm ci

    - name: Install Sigma CLI plugins
      run: sigma plugin install splunk

    - name: SigmaルールをSplunk形式に変換
      run: |


    - name: Splunk形式のルールをコミット
      run: |
        git add -N rules/splunk
        if [ -z "$(git diff --exit-code rules/splunk)" ]; then
          echo "No changes to commit"
          exit 0
        else
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add rules/splunk
          git commit -m "Convert Sigma rules to Splunk"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the website
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
